In [1]:
import numpy as np

a = np.random.randn(5)

In [2]:
print(a)

[-1.15298935 -0.00523271 -1.36288584  1.81442075  0.3373072 ]


In [3]:
print(a.shape)

(5,)


In [4]:
print(a.T)

[-1.15298935 -0.00523271 -1.36288584  1.81442075  0.3373072 ]


In [5]:
print(np.dot(a, a.T))

6.592768435627088


In [6]:
a = np.random.randn(5, 1)
print(a)

[[ 0.60572082]
 [ 0.80740465]
 [ 0.98213898]
 [-0.60724865]
 [ 0.3789569 ]]


In [7]:
print(a.T)

[[ 0.60572082  0.80740465  0.98213898 -0.60724865  0.3789569 ]]


In [8]:
print(np.dot(a, a.T))

[[ 0.36689771  0.48906181  0.59490203 -0.36782315  0.22954208]
 [ 0.48906181  0.65190227  0.79298358 -0.49029538  0.30597156]
 [ 0.59490203  0.79298358  0.96459698 -0.59640257  0.37218834]
 [-0.36782315 -0.49029538 -0.59640257  0.36875092 -0.23012107]
 [ 0.22954208  0.30597156  0.37218834 -0.23012107  0.14360833]]
